### ISSUE TITLE
Issue while executing the script - Please help

### ISSUE THREAD

**Issue by praveensinghinfo** [MikeMeliz/TorCrawl.py#18]
Traceback (most recent call last):
  File "torcrawl.py", line 218, in <module>
    main()
  File "torcrawl.py", line 176, in main
    if int(args.yara) not in [0, 1]:
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by the-siegfried** [comment]
Hi @hackgod512, 

Apologies for the belated response. Were you able to resolve the issue? 
If you were notable to resolve the issue, please could you retry and document the steps you took to reproduce the error. 

Kind Regards, 
@the-siegfried

**Comment by MikeMeliz** [comment]
It should be fixed here, and yara argument is not needed to get a simple extract: https://github.com/MikeMeliz/TorCrawl.py/commit/35d2874f324889d5f4daf777fd8d4532706ecb86

If anyone get the same error again, feel free to re-open the issue :)
