### ISSUE TITLE
Tor connection error 

### ISSUE THREAD

**Issue by parthk2510** [MikeMeliz/TorCrawl.py#20]
I am trying to use it but getting tor error even when tor is working 
![Screenshot_2022-07-06_14-23-06](https://user-images.githubusercontent.com/87540263/177513587-7bade7ff-ee2f-4374-844f-1c5cdde39402.png)
![Screenshot_2022-07-06_14-34-09](https://user-images.githubusercontent.com/87540263/177513602-af44613a-1181-439c-bf88-e5697d9bd256.png)
 Can you help ?
Also do I need to configure proxychain?

**Comment by H0uss** [comment]
Hello, did you manage to solve this problem ?

**Comment by MikeMeliz** [comment]
Super delayed answer also here, but I just tried to replicate and I can't get the same error, even though it seems like a simple syntax error in this print.

For future reference, try with duckduckgo's onion website, to make sure that tor is working.
Eg. `python3 torcrawl.py -u https://duckduckgogg42xjoc72x3sjasowoarfbgcmvfimaftt6twagswzczad.onion/`
