### ISSUE TITLE
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

### ISSUE THREAD

**Issue by santosadrian** [MikeMeliz/TorCrawl.py#22]
(base) root@pimp3:~/TorCrawl.py# python3 torcrawl.py -v -u darkfailenbsdla5mal2mxn2uz66od5vtzd5qozslagrfzachha3f3id.onion -c -d 999 -p 1
Traceback (most recent call last):
  File "torcrawl.py", line 218, in <module>
    main()
  File "torcrawl.py", line 176, in main
    if int(args.yara) not in [0, 1]:
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by dennisosaj** [comment]
Put "-y 0" into your query.

**Comment by MikeMeliz** [comment]
Another delayed answer here, but I'm trying today to make yara not to confuse the new users. First, many thanks @dennisosaj for helping here!

I've changed it in this commit here: https://github.com/MikeMeliz/TorCrawl.py/commit/35d2874f324889d5f4daf777fd8d4532706ecb86 that yara module and argument won't be really needed for any run. So simple queries like `torcrawl.py -u google.com` will work again!
