### ISSUE TITLE
I want extract image from this crawl

### ISSUE THREAD

**Issue by Omid-r** [MikeMeliz/TorCrawl.py#3]
hello guys:.
I want extract image from the torcrawl
I can't well edite extract.py because I don't now about founction of this .py
please help me..

**Comment by MikeMeliz** [comment]
Hello Omid-r!

Thanks for posting an issue for my script 👍 I'd be glad to help you with that!

As you can see on [modules/crawler.py](https://github.com/MikeMeliz/TorCrawl.py/blob/master/modules/crawler.py), I made a function `excludes` (line: 36) to exclude some type of links for further crawling. But for some usefull links (external links, telephones, mails) I'm making a .txt to save the URLs for other uses.

Is a .txt with image's URLs good for your case? Or are you looking to save the images on a folder?

**Comment by Omid-r** [comment]
Thanks a lot Maike 👍 
Yes I want save the images on a folder..
But I don't now how I can do that ..Please guidance me..
How I can use line:36 in main program : torcrawl.py or exetractor.py?

**Comment by MikeMeliz** [comment]
I found a quick workaround/start-point but I'm **really** not sure about the results:

Replace on [modules/crawler.py](https://github.com/MikeMeliz/TorCrawl.py/blob/master/modules/crawler.py) lines 105-112 with this:
```python
# For each <img src="">
for img in soup.findAll('img')
  imglink = img.get('src')
  canonicalimage = canonical(imglink, website)
  outputfile = open(outpath + '/images.txt', 'w+')
  outputfile.write(canonicalimage + '\n')
  outputfile.close()
```
That part will create for you a list of images on website's folder. 

So, probably a combine of TorCrawl and Wget will work for you:
```$ python torcrawl.py -w -v -u github.com -c && wget -i github.com/images.txt```
or
```$ python torcrawl.py -v -u github.com -c && torsocks wget -i github.com/images.txt```

Please, let me know if you figure out a better way

**Comment by Omid-r** [comment]
<img width="625" alt="screen shot 1396-03-07 at 11 43 47" src="https://cloud.githubusercontent.com/assets/28532153/26526806/f7a478ec-439a-11e7-99ba-04c15e64465c.png">
👍 :
I 'm geting a syntax error when I using that ..
<img width="723" alt="screen shot 1396-03-07 at 11 46 12" src="https://cloud.githubusercontent.com/assets/28532153/26526814/4dbdb5f4-439b-11e7-8305-ac519d10198d.png">

**Comment by MikeMeliz** [comment]
*Oups*, of course.. 🤕
We need an ':' on this loop:
```python
for img in soup.findAll('img'):
```
Also, because script fix a bit the URLs, in wget we have to add "www." in front of folder.

By the way, I'll try to find a better way to extract image's links

**Comment by Omid-r** [comment]
Hello Mike ..Thanks for your help my friend...
I fix this and It's runinig  but I get this error..
<img width="666" alt="screen shot 1396-03-08 at 10 01 51" src="https://cloud.githubusercontent.com/assets/28532153/26537597/1ab2d246-4456-11e7-8368-b887df336d42.png">

**Comment by MikeMeliz** [comment]
Hey Omid-r!

That's actually weird, because on [crawler.py](https://github.com/MikeMeliz/TorCrawl.py/blob/master/modules/crawler.py) we call the module with the proper way ([reference](https://stackoverflow.com/a/20444712/5418174)).

You can probably try the other way to call the module and change the following lines to:
[modules/crawler.py(Line:8)](https://github.com/MikeMeliz/TorCrawl.py/blob/master/modules/crawler.py#L8): ```import BeautifulSoup```
[modules/crawler.py(Line:93)](https://github.com/MikeMeliz/TorCrawl.py/blob/master/modules/crawler.py#L93): ```soup = BeautifulSoup.BeautifulSoup(html_page)```

Also, please check that you already have installed BeautifulSoup on python terminal with:
```>>>import BeautifulSoup```

**Comment by Omid-r** [comment]
I fix that thanks how I can fix this?
<img width="813" alt="screen shot 1396-03-08 at 10 44 12" src="https://cloud.githubusercontent.com/assets/28532153/26538421/dad77bee-445b-11e7-83a0-142b50027df0.png">

**Comment by MikeMeliz** [comment]
I'm glad to hear it worked well for you!

As I can see from your screenshot you're on MacBook, so it's normal that wget command didn't found.

I found on stackoverflow ([here](https://stackoverflow.com/a/20912978/5418174)) a similar way to download the list of images:
```
cd www.github.com/
for i in "`cat /images.txt`" ; do curl -O "$i" ; done
```

**Comment by Omid-r** [comment]
<img width="639" alt="screen shot 1396-03-08 at 16 32 19" src="https://cloud.githubusercontent.com/assets/28532153/26549067/6dc7109c-448c-11e7-89d1-fb677a9848aa.png">

**Comment by Omid-r** [comment]
Hello Mike
Please guide me
I handel errors..but now this's wierd..
Omids-MacBook-Pro:untitled Omid$ python torcrawl.py -w -v -u github.com -c && wget -i www.github.com/images.txt
## Your IP: 5.235.142.60
## URL: github.com
## URL fixed: www.github.com
## URL fixed: http://www.github.com
## Folder created: www.github.com
## Crawler Started from http://www.github.com with step 1 and wait None
## Step 1 completed with: 22 results
## File created on /Users/Omid/PycharmProjects/untitled/www.github.com/links.txt
No URLs found in www.github.com/images.txt.

Although Images.txt It was made but it's empty
And "No URLs found in www.github.com/images.txt." 
I think something is wrong...

**Comment by MikeMeliz** [comment]
Hey @Omid-r ! Sorry but I was busy last week.
For the case of Github (that's using sub-domain to host images), you can try this:

[/modules/crawler.py@105](https://github.com/MikeMeliz/TorCrawl.py/blob/master/modules/crawler.py#L105): 
```python
# For each <img src="">
outputfile = open(outpath + '/images.txt', 'w+')
for img in soup.findAll('img'):
  imglink = img.get('src')
  if imglink != None: # Can't figure out why this occurs
    outputfile.write(imglink + '\n')
outputfile.close()
```
Please keep in mind this is a small work-around and not any final solution. Edit the code for your specific scenario.

**Comment by MikeMeliz** [comment]
I'll close this question.

- If you need any further help, leave me a comment here.
- If you found out a successful way to crawl image's links, make a pull request and I'll be happy to review and merge it :)

**Comment by Omid-r** [comment]
Ok Mike Thanks.
